### ISSUE TITLE
what happen???

### ISSUE THREAD

**Issue by LZZhideonbush** [lucasjinreal/fasterrcnn_pytorch#1]
Traceback (most recent call last):
  File "train_voc.py", line 31, in <module>
    from lib.model.faster_rcnn.vgg16 import vgg16
  File "/home/userroot/fasterrcnn_pytorch/lib/model/faster_rcnn/vgg16.py", line 16, in <module>
    from ..faster_rcnn.faster_rcnn import _fasterRCNN
  File "/home/userroot/fasterrcnn_pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 10, in <module>
    from ..rpn.rpn import _RPN
  File "/home/userroot/fasterrcnn_pytorch/lib/model/rpn/rpn.py", line 8, in <module>
    from .proposal_layer import _ProposalLayer
  File "/home/userroot/fasterrcnn_pytorch/lib/model/rpn/proposal_layer.py", line 21, in <module>
    from ..roi_layers import nms
  File "/home/userroot/fasterrcnn_pytorch/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/userroot/fasterrcnn_pytorch/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ModuleNotFoundError: No module named 'model'

**Comment by lucasjinreal** [comment]
@LZZhideonbush  Sorry, this work not finish yet as currently I am not focus on two-stage detection methods
